package exception;

public class Exception1 {

	public static void main(String[] args) {
		try {
			System.out.println("2. 문제 발생코드" + 10/0);
			
		} catch (Exception e) {
			System.out.println("에러 발생함.");
		}
	}

}
